### ISSUE TITLE
PC识别结果和手机识别结果不一致

### ISSUE THREAD

**Issue by suguoyao** [zh8637688/wx-cardscanner#4]
PC端识别率挺高的，但我在IOS识别的结果太不准了，不知道是不是UPNG处理这块有兼容问题呢？

**Comment by suguoyao** [comment]
作者能留个联系方式不，可以交流一下哈

**Comment by baolele** [comment]
我也遇到了同样的问题,pc端和android端识别率都挺高的,但是ios的识别率极低

**Comment by zh8637688** [comment]
@suguoyao 给个测试用的图

**Comment by zh8637688** [comment]
@baolele good
#1
